GET http://localhost:3000/subscribers/


###

GET http://localhost:3000/subscribers/608e8efaa71f8c240cbc8180

###


POST http://localhost:3000/subscribers
Content-Type: application/json
{
    "name":"lyle",
"subscribedToChannel": "Internet today"
}

###

DELETE http://localhost:3000/subscribers/608e8c4c0193d8448cd523a8